sudo: false
language: c
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]$/
matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      python: "3.7"
    - os: linux
      arch: arm64
      dist: bionic
      language: python
      python: "3.7"
    - os: linux
      arch: arm64-graviton2
      dist: bionic
      group: edge
      virt: lxd
      language: python
      python: "3.7"
script:
  - python run.py deps
  - python run.py ci
